config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import accounts_urls
from nfs import nfs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nfs/', include(nfs_urls)),
    path('', include(accounts_urls)),
    path('scan/', include('scanapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    HOD = '1'
    STAFF = '2'
    STUDENT = '3'

    EMAIL_TO_USER_TYPE_MAP = {
        'hod': HOD,
        'staff': STAFF,
        'student': STUDENT
    }

    user_type_data = ((HOD, "HOD"), (STAFF, "Staff"), (STUDENT, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)


class Group(models.Model):
    number = models.CharField(max_length=10, verbose_name="Gruh nomeri")
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.number


class AdminHOD(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)


class Staffs(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='staff')
    address = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)


class Students(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='student')
    id = models.AutoField(primary_key=True)
    FIO = models.CharField(max_length=500, verbose_name='FIO')
    passport_id = models.CharField(max_length=15, verbose_name="Pasport ID")
    JSHSHIR = models.CharField(max_length=50)
    fuqarolik = models.CharField(max_length=300)
    country = models.CharField(max_length=100)
    nationaly = models.CharField(max_length=100, verbose_name='Millat')
    region = models.CharField(max_length=100, verbose_name='viloyat', blank=True, null=True)
    tuman = models.CharField(max_length=100, verbose_name='tuman', blank=True, null=True)
    gender = models.CharField(max_length=50, verbose_name='jins')
    brithday = models.CharField(max_length=100, verbose_name="Tugulgan sana")
    faculty = models.CharField(max_length=300, verbose_name="Fakultet")
    groups = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)
    typeofEducation = models.CharField(max_length=100, name="Talim turi")
    formofEducation = models.CharField(max_length=100, verbose_name="Talim shakli")
    phone_number = models.CharField(max_length=20, verbose_name="Telefon raqami")
    nfcId = models.CharField(max_length=50)
    passCode = models.IntegerField(default=1234)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.FIO


class Accept_Book(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='accept_book')
    staff = models.CharField(max_length=100, verbose_name='Bergan odam nomi')
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    key = models.CharField(max_length=25, unique=True)
    respite = models.DateTimeField(blank=True, null=True)
    date = models.DateField(editable=False, auto_now_add=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


class Return_Book(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=True, null=True)
    staff = models.CharField(max_length=100, verbose_name='Bergan odam nomi')
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    date = models.DateTimeField(verbose_name="olingan vaqti", blank=True, null=True)
    key = models.CharField(max_length=25)
    respite = models.DateTimeField(blank=True, null=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


class SendMessages(models.Model):
    name = models.CharField(max_length=100, verbose_name='Ism', blank=True)
    title = models.CharField(max_length=100, verbose_name='Mavzu')
    body = models.CharField(max_length=1000, verbose_name='Xabar matni')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name


class Check(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    date = models.DateField(verbose_name="olingan vaqti", blank=True, null=True)
    key = models.CharField(max_length=25, unique=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


class EmplayeeMessages(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name


class Book(models.Model):
    book_name = models.CharField(max_length=100, verbose_name='Китоб номи', blank=True, null=True)
    key = models.CharField(max_length=25, verbose_name='Инвентар рақами', unique=True)
    author = models.CharField(max_length=100, verbose_name='Муаллифи', blank=True, null=True)
    organization = models.CharField(max_length=200, verbose_name="Тавсия қилган ташкилот", blank=True, null=True)
    publishing = models.CharField(max_length=100, verbose_name="Нашриёт", blank=True, null=True)
    book_type = models.CharField(max_length=25, blank=True, null=True)
    language = models.CharField(max_length=25, blank=True, null=True)
    year = models.CharField(max_length=50, verbose_name="Йили", blank=True, null=True)
    beti = models.CharField(max_length=50, verbose_name="Бети", blank=True, null=True)
    isbn = models.CharField(max_length=50, verbose_name="ISBN")
    money = models.CharField(max_length=25, verbose_name="Сумма", blank=True, null=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name[:50]


class NfcCheck(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='nfc_check')
    staff = models.CharField(max_length=100, verbose_name='Bergan odam nomi')
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    key = models.CharField(max_length=25, unique=True)
    respite = models.DateTimeField(blank=True, null=True)
    date = models.DateField(editable=False, auto_now_add=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)
    checker = models.DateTimeField()

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


@receiver(post_save, sender=CustomUser)
# Now Creating a Function which will
# automatically insert data in HOD, Staff or Student
def create_user_profile(sender, instance, created, **kwargs):
    # if Created is true (Means Data Inserted)
    if created:

        # Check the user_type and insert the data in respective tables
        if instance.user_type == 1:
            AdminHOD.objects.create(admin=instance)
        if instance.user_type == 2:
            Staffs.objects.create(admin=instance)
        if instance.user_type == 3:
            Students.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminhod.save()
    if instance.user_type == 2:
        instance.staff.save()
    if instance.user_type == 3:
        instance.student.save()

templates/staff/all_book.html
{% extends 'staff/base/base.html' %}
{% load static %}

{% block title %}
  Kitoblar
{% endblock title %}

{% block style %}
  <link rel="stylesheet" href="{%static 'staff/all_book_style.css' %}"> 
{% endblock style %}
  
{% block content %}
<div class="all-books-container">
  <h3 class="give-book-title">Mavjud kitoblar</h3>
<div class="choose-input">
  <form method="post">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Kitob izlash" required />
    <button type="submit">Qidirish</button>
  </form>
</div>
<div class="members-table">
  <table class="main-table">
    <thead>
      <tr class="main-table_tr">
        <th>T/R</th>
        <th>Kitob nomi</th>
        <th>Muallifi</th>
        <th>Inventar raqami</th>
      </tr>
    </thead>
    <tbody>
      {% for book in book %}
      <tr class="main-table_tr">
        <td class="main-table_td">{{ forloop.counter }}</td>
        <td class="main-table_td">
          {{ book.book_name }}
        </td>
        <td class="main-table_td">
          {{ book.author }}
        </td>
        <td class="main-table_td">{{ book.key }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{% endblock content %}
    

templates/staff/contact.html
{% extends 'staff/base/base.html' %}
{% load static %} 
{% block title %} 
Bog'lanish
{% endblock title %} 
{% block style %}
<link rel="stylesheet" href="{% static 'student/contact.css' %}" />
{% endblock style %} {% block content %}
<section class="container">
  <div class="creaters-box">
    <div class="createrr-box">
      <div class="creater-box">
        <div class="creater-image">
          <img
            src="{% static 'student/image/foto.jpg' %}"
            alt="creater image"
          />
        </div>
        <div class="creater-info">
          <h4 class="creater-fio">Masharipov Nodirbek</h4>
          <h4 class="creater-gmail">friend18337@gmail.com</h4>
          <div class="social-links">
            <a href="#">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-telegram"
                viewBox="0 0 16 16"
              >
                <path
                  d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"
                />
              </svg>
            </a>
            <a href="#">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-instagram"
                viewBox="0 0 16 16"
              >
                <path
                  d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"
                />
              </svg>
            </a>
            <a href="#">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-twitter"
                viewBox="0 0 16 16"
              >
                <path
                  d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"
                />
              </svg>
            </a>
            <a href="#">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-youtube"
                viewBox="0 0 16 16"
              >
                <path
                  d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"
                />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/staff/profile_talaba.html
{% extends 'staff/base/base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'staff/services/give_book_style.css' %}" />
{% endblock style %}

{% block title %}
    Kitob qaytarish
{% endblock title %}


{% block content %}
<div class="book-container">
<h3 class="give-book-title">Talaba profili</h3>
<div class="select-div">
    <form method="post">
        {% csrf_token %}
        <select name="group" class="form-control" onchange="this.form.submit()">
            <option>Guruh tanlash</option>
            {% for group_id in group %}
            <option value="{{ group_id.id }}">{{ group_id.number }}</option>
            {% endfor %}
        </select>
    </form>
</div>
<table class="main-table">
    <h4 class="group-students">{{ g }} Guruh talabalari</h4>
    <thead>
        <tr class="main-table_tr">
            <th>T/r</th>
            <th>F.I.Sh</th>
            <th>Guruh</th>
            <th>Pasport ID</th>
            <th>Telefon raqam</th>
            <th>Tanlash</th>
        </tr>
    </thead>
    <tbody>
        {% for student in member %}
        <tr class="main-table_tr">
            <th class="main-table_td">{{ forloop.counter }}</th>
            <th class="main-table_td">{{ student.FIO }}</th>
            <th class="main-table_td">{{ student.groups }}
            </th>
            <th class="main-table_td">{{ student.passport_id }}</th>
            <th class="main-table_td">{{ student.phone_number }}</th>
            <th class="main-table_td pen-box">
                <div class="pen-boxx">
                    <a href="profile/{{ student.id }}">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        fill="currentColor"
                        class="bi bi-pen-fill"
                        viewBox="0 0 16 16"
                      >
                        <path
                          d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"
                        />
                      </svg>
                    </a>
                  </div>

            </th>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock content %}

templates/staff/sendMessages.html
{% extends "staff/base/base.html" %}
{% load static %}
{% block title %}
Xabar yuborish
{% endblock title %}
{% block style %}
  <link rel="stylesheet" href="{% static 'staff/sendmessage_style.css' %}">
{% endblock style %}
{% block content %}
<div class="main-center">
  <div class="main-div">
    <p class="message-title">Talabalarga xabar yuborish</p>
    <form method="post" class="myform">
      {% csrf_token %}
      <div class="message-thema">
        <p class="thema-title">Xabar mavzusi:</p>
        <textarea name="title" cols="30" rows="2" maxlength="100" class="thema-textarea" required></textarea>
      </div>
      <div class="message-about">
        <p class="message-about-title">Xabar matni:</p>
        <textarea name="message" id="" cols="30" rows="2" maxlength="1000" class="message-about-text" required></textarea>
      </div>
      <button type="submit" class="submit-btn">Yuborish</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/staff/statistics.html
{% extends 'staff/base/base.html' %}
{% load static %}

{% block title %}
  Kitobhonlar
{% endblock title %}

{% block style %}
  <link rel="stylesheet" href="{% static 'staff/services/allreading_style.css' %}">
{% endblock style %}
   
{% block content %}
<div class="booksers-container">
<h3 class="give-book-title">Faol kitobxonlar</h3>
<div class="members-table">
  <table class="main-table">
    <thead>
      <tr class="main-table_tr">
        <th scope="col">T/R</th>
        <th scope="col">F.I.Sh</th>
        <th>Guruh</th>
        <th scope="col">O'qigan kitoblari soni</th>
      </tr>
    </thead>
    <tbody>
      {% for name in statistics %}
      <tr class="main-table_tr">
        <td class="main-table_td">{{ forloop.counter }}</th>
        <td class="main-table_td">{{ name.FIO }}</td>
        <td class="main-table_td">{{ name.groups }}</td>
        <td class="main-table_td">{{ name.return_book_set.all.count }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/staff/talaba.html
{% extends 'staff/base/base.html' %}
{% load static %}
{% block title %}
STUDENT
{% endblock title %}
{% block style %}
<link rel="stylesheet" href="{% static 'student/profile.css' %}" />
{% endblock style %} {% block content %}
<div class="container">
  <div class="container1">
    <div class="profile-image-left">
      <img src="{% static '149071.png' %}" alt="student image" />
      <h4 class="student-fio">{{student.FIO}}</h4>
    </div>
    <div class="profile-info-right">
      <div class="student-div-right">
        <h4 class="student-right-title">F.I.Sh:</h4>
        <h4 class="student-left-title">
          {{ student.FIO }}
        </h4>
      </div>
      <div class="student-div-right">
        <h4 class="student-right-title">Talaba ID:</h4>
        <h4 class="student-left-title">{{ student.admin.username }}</h4>
      </div>
      <div class="student-div-right">
        <h4 class="student-right-title">Telefon raqam:</h4>
        <h4 class="student-left-title">{{ student.phone_number }}</h4>
      </div>
      <div class="student-div-right">
        <h4 class="student-right-title">Pasport raqam:</h4>
        <h4 class="student-left-title">{{ student.passport_id }}</h4>
      </div>
      <div class="student-div-right">
        <h4 class="student-right-title">Guruh raqam:</h4>
        <h4 class="student-left-title">{{ student.groups }}</h4>
      </div>
    </div>
  </div>
  <div class="members-table">
    <table class="main-table">
      <thead>
        <tr class="main-table_tr">
          <th>T/R</th>
          <th>Kitob nomi</th>
          <th>Kitob inventar raqami</th>
          <th>Muhlat</th>
          <th>Olgan vaqti</th>
          <th>Bergan vaqti</th>
        </tr>
      </thead>
      {% for acceptbook in accept_book %}
      <tbody>
        <tr class="main-table_tr">
          <td class="main-table_td">{{ forloop.counter }}</td>
          <td class="main-table_td">{{ acceptbook.book_name }}</td>
          <td class="main-table_td">{{ acceptbook.key }}</td>
          <td class="main-table_td">{{ acceptbook.respite }}</td>
          <td class="main-table_td">{{ acceptbook.date }}</td>
          <td class="main-table_td">Qaytarilmagan</td>
        </tr>
      </tbody>
      {% endfor %}
      {% for returnBook in return_book %}
      <tbody>
        <tr class="main-table_tr">
          <td class="main-table_td">{{ forloop.counter }}</td>
          <td class="main-table_td">{{ returnBook.book_name }}</td>
          <td class="main-table_td">{{ returnBook.key }}</td>
          <td class="main-table_td">{{ returnBook.respite }}</td>
          <td class="main-table_td">{{ returnBook.date }}</td>
          <td class="main-table_td">{{ returnBook.created }}</td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock content %}