config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import accounts_urls
from nfs import nfs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('nfs/', include(nfs_urls)),
    path('', include(accounts_urls)),
    path('scan/', include('scanapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    HOD = '1'
    STAFF = '2'
    STUDENT = '3'

    EMAIL_TO_USER_TYPE_MAP = {
        'hod': HOD,
        'staff': STAFF,
        'student': STUDENT
    }

    user_type_data = ((HOD, "HOD"), (STAFF, "Staff"), (STUDENT, "Student"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)


class Group(models.Model):
    number = models.CharField(max_length=10, verbose_name="Gruh nomeri")
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.number


class AdminHOD(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)


class Staffs(models.Model):
    id = models.AutoField(primary_key=True)
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='staff')
    address = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)


class Students(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name='student')
    id = models.AutoField(primary_key=True)
    FIO = models.CharField(max_length=500, verbose_name='FIO')
    passport_id = models.CharField(max_length=15, verbose_name="Pasport ID")
    JSHSHIR = models.CharField(max_length=50)
    fuqarolik = models.CharField(max_length=300)
    country = models.CharField(max_length=100)
    nationaly = models.CharField(max_length=100, verbose_name='Millat')
    region = models.CharField(max_length=100, verbose_name='viloyat', blank=True, null=True)
    tuman = models.CharField(max_length=100, verbose_name='tuman', blank=True, null=True)
    gender = models.CharField(max_length=50, verbose_name='jins')
    brithday = models.CharField(max_length=100, verbose_name="Tugulgan sana")
    faculty = models.CharField(max_length=300, verbose_name="Fakultet")
    groups = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)
    typeofEducation = models.CharField(max_length=100, name="Talim turi")
    formofEducation = models.CharField(max_length=100, verbose_name="Talim shakli")
    phone_number = models.CharField(max_length=20, verbose_name="Telefon raqami")
    nfcId = models.CharField(max_length=50)
    passCode = models.IntegerField(default=1234)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.FIO


class Accept_Book(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='accept_book')
    staff = models.CharField(max_length=100, verbose_name='Bergan odam nomi')
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    key = models.CharField(max_length=25, unique=True)
    respite = models.DateTimeField(blank=True, null=True)
    date = models.DateField(editable=False, auto_now_add=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


class Return_Book(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=True, null=True)
    staff = models.CharField(max_length=100, verbose_name='Bergan odam nomi')
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    date = models.DateTimeField(verbose_name="olingan vaqti", blank=True, null=True)
    key = models.CharField(max_length=25)
    respite = models.DateTimeField(blank=True, null=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


class SendMessages(models.Model):
    name = models.CharField(max_length=100, verbose_name='Ism', blank=True)
    title = models.CharField(max_length=100, verbose_name='Mavzu')
    body = models.CharField(max_length=1000, verbose_name='Xabar matni')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name


class Check(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    date = models.DateField(verbose_name="olingan vaqti", blank=True, null=True)
    key = models.CharField(max_length=25, unique=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


class EmplayeeMessages(models.Model):
    name = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name


class Book(models.Model):
    book_name = models.CharField(max_length=100, verbose_name='Китоб номи', blank=True, null=True)
    key = models.CharField(max_length=25, verbose_name='Инвентар рақами', unique=True)
    author = models.CharField(max_length=100, verbose_name='Муаллифи', blank=True, null=True)
    organization = models.CharField(max_length=200, verbose_name="Тавсия қилган ташкилот", blank=True, null=True)
    publishing = models.CharField(max_length=100, verbose_name="Нашриёт", blank=True, null=True)
    book_type = models.CharField(max_length=25, blank=True, null=True)
    language = models.CharField(max_length=25, blank=True, null=True)
    year = models.CharField(max_length=50, verbose_name="Йили", blank=True, null=True)
    beti = models.CharField(max_length=50, verbose_name="Бети", blank=True, null=True)
    isbn = models.CharField(max_length=50, verbose_name="ISBN")
    money = models.CharField(max_length=25, verbose_name="Сумма", blank=True, null=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name[:50]


class NfcCheck(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE, related_name='nfc_check')
    staff = models.CharField(max_length=100, verbose_name='Bergan odam nomi')
    created = models.DateTimeField(editable=False, auto_now_add=True)
    book_name = models.CharField(max_length=50, verbose_name="Kitob nomi")
    author = models.CharField(max_length=100, verbose_name='Муаллифи')
    key = models.CharField(max_length=25, unique=True)
    respite = models.DateTimeField(blank=True, null=True)
    date = models.DateField(editable=False, auto_now_add=True)
    objects = models.Manager()
    created_at = models.DateTimeField(auto_now_add=True)
    checker = models.DateTimeField()

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.book_name


@receiver(post_save, sender=CustomUser)
# Now Creating a Function which will
# automatically insert data in HOD, Staff or Student
def create_user_profile(sender, instance, created, **kwargs):
    # if Created is true (Means Data Inserted)
    if created:

        # Check the user_type and insert the data in respective tables
        if instance.user_type == 1:
            AdminHOD.objects.create(admin=instance)
        if instance.user_type == 2:
            Staffs.objects.create(admin=instance)
        if instance.user_type == 3:
            Students.objects.create(admin=instance)


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminhod.save()
    if instance.user_type == 2:
        instance.staff.save()
    if instance.user_type == 3:
        instance.student.save()

templates/staff/settings/add_book.html
{% extends 'staff/base/base.html' %}
{% load static %} 
{% block title %} 
Kitob qoshish
{% endblock title %} 
{% block style %}
<link rel="stylesheet" href="{% static 'staff/settings/add_book_style.css' %}" />
{% endblock style %} {% block content %}

<h3 class="add_a_book-title">Kitob qo'shish</h3>
<div class="inputs-and-buttons-box">
  <div class="inputs-box">
    <form method="post" role="form">
      {% csrf_token %}
      <div class="inputss-box">
        <div class="input-top">
          <input type="text" name="book_name" placeholder="Kitob nomi" required />
          <input type="text" name="author" placeholder="Muallifi" required />
        </div>
        <div class="input-bottom">
          <input
            type="text"
            name="book_type"
            placeholder="Kitob turi"
            class="first-input"
            required
          />
          <input
            type="text"
            name="key"
            placeholder="Inventar raqam"
            class="second-input"
            required
          />
          <input
            type="text"
            name="lang"
            placeholder="Kitob tili"
            class="third-input"
            required
          />
        </div>
      </div>
      <div class="input-buttonss">
        <button type="submit" class="input-buttons" name="book_type">
          Qo'shish
        </button>
        {% if image %}
        <a class="a-button" href="data:image/png;base64,{{ image }}" download>
          Yuklash
        </a>
        {% else %}
        <a class="a-button" href="{% url 'upload_book' %}">
            Fayl yuklash
        </a>
        {% endif %}
      </div>
    </form>
  </div>
</div>

<div class="error-message-div">
  {% for messages in messages %} <p class="error-message-title">{{ messages }}</p> {% endfor %}
</div>

<div class="members-table">
  <table class="main-table">
    <thead>
      <tr class="main-table_tr">
        <th>T/R</th>
        <th>Kitob nomi</th>
        <th>Muallifi</th>
        <th>Inventar raqami</th>
        <th>Turi</th>
        <th>Tili</th>
      </tr>
    </thead>
    <tbody>
      {% for book in book %}
      <tr class="main-table_tr">
        <td class="main-table_td">{{ forloop.counter }}</td>
        <td class="main-table_td">{{ book }}</td>
        <td class="main-table_td">{{ book.author }}</td>
        <td class="main-table_td">{{ book.key }}</td>
        <td class="main-table_td">{{ book.book_type }}</td>
        <td class="main-table_td">{{ book.language }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/staff/settings/add_students.html
{% extends 'staff/base/base.html' %} 
{% load static %} 
{% block title %} 
Student qo'shish 
{% endblock title %} 
{% block style %}
<link rel="stylesheet" href="{% static 'staff/settings/add_students.css' %}" />
{% endblock style %} 
{% block content %}
<h3 class="add_student-title">Talaba qo'shish</h3>
<div class="top-box">
  <form method="post">
    {% csrf_token %}
    <div class="inputs-box">
      <div class="top-inputs">
        <input
          type="text"
          name="FIO"
          placeholder="F.I.Sh"
          class="fio-input"
          required
        />
        <input
          type="text"
          name="password_ID"
          placeholder="Pasport ID"
          class="id-input"
          required
        />
        <input
          type="text"
          name="password"
          placeholder="Parol"
          class="parol-input"
          required
        />
      </div>
      <div class="bottom-inputs">
        <input
          type="text"
          name="username"
          placeholder="Talaba ID"
          class="username-input"
          required
        />
        <input
          type="text"
          name="phone_number"
          placeholder="Telefon raqami"
          class="tel-input"
          required
        />
        <div class="select-div">
          <select
            name="group"
            class="form-control rounded"
            aria-label="Default select example"
          >
            <option>Guruh raqami</option>
            {% for group_id in group_id %}
            <option value="{{ group_id.id }}">{{ group_id.number }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
    </div>
    <div class="inputt-buttons">
      <button class="inputs-button" type="submit">Qo'shish</button>
      <a class="a-button" href="{% url 'upload_student' %}">
        Fayl yuklash
      </a>
    </div>
  </form>
</div>

<div class="error-message-div">
  {% for messages in messages %} <p class="error-message-title">{{ messages }}</p> {% endfor %}
</div>

<div class="members-table">
  <table class="main-table">
    <thead>
      <tr class="main-table_tr">
        <th>T/R</th>
        <th>F.I.Sh</th>
        <th>Guruh raqami</th>
        <th>Pasport ID</th>
        <th>Telefon raqami</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
      <tr class="main-table_tr">
        <td class="main-table_td">{{ forloop.counter }}</td>
        <td class="main-table_td">{{ student.student.FIO }}</td>
        <td class="main-table_td">{{ student.student.groups }}</td>
        <td class="main-table_td">{{ student.student.passport_id }}</td>
        <td class="main-table_td">{{ student.student.phone_number }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

templates/staff/settings/del_book.html
{% extends "staff/base/base.html" %}
{% load static %}
{% block title %}
Kitob o'chirish
{% endblock title %}
{% block style %}
<link
  rel="stylesheet"
  href="{% static 'staff/settings/del_book_style.css' %}"
/>
{% endblock style %} 
{% block content %}

<h3 class="give-book-title">Kitob o'chirish</h3>
<div class="choose-input">
  <form method="post">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Kitob izlash" required />
    <button type="submit">Izlash</button>
  </form>
</div>
<div class="members-table">
  <table class="main-table">
    <thead>
      <tr class="main-table_tr">
        <th>T/R</th>
        <th>Kitob nomi</th>
        <th>Muallifi</th>
        <th>Inventar raqami</th>
        <th>O'chirish</th>
      </tr>
    </thead>
    <tbody>
    {% for book in book %}
      <tr class="main-table_tr">
        <td class="main-table_td">{{ forloop.counter }}</td>
        <td class="main-table_td">{{ book.book_name }}</td>
        <td class="main-table_td">{{ book.author }}</td>
        <td class="main-table_td">{{ book.key }}</td>
        <td class="main-table_td pen-box">
          <div class="pen-boxx">
            <a href="{% url 'del_book_id' book.id %}">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-trash"
                viewBox="0 0 16 16"
              >
                <path
                  d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"
                />
                <path
                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"
                />
              </svg>
            </a>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

templates/staff/settings/del_students.html
{% extends 'staff/base/base.html' %}
{% load static %}
{% block title %}STUDENT O'CHIRISH{% endblock title %}
{% block style %}
<link
  rel="stylesheet"
  href="{% static 'staff/settings/del_student_style.css' %}"
/>
{% endblock style %}
{% block content %}
<h3 class="give-book-title">Talaba o'chirish</h3>
<div class="select-div">
  <form method="post">
    {% csrf_token %}
    <select name="group"  onchange="this.form.submit()">
      <option>Guruhni tanlash</option>
      {% for group_id in group %}
      <option value="{{ group_id.id }}">{{ group_id.number }}</option>
      {% endfor %}
    </select>
  </form>
</div>
<h4 class="group-students">{{ g }} Guruh talabalari</h4>
<div class="members-table">
  <table class="main-table">
    <thead>
      <tr class="main-table_tr">
        <th>T/R</th>
        <th>F.I.O</th>
        <th>Guruh nomer</th>
        <th>PasportID</th>
        <th>Telefon raqam</th>
        <th>O'chirish</th>
      </tr>
    </thead>
    <tbody>
      {% for student in student %}
      <tr class="main-table_tr">
        <td class="main-table_td">{{ forloop.counter }}</td>
        <td class="main-table_td">{{ student.student.FIO }}</td>
        <td class="main-table_td">{{ student.student.groups }}</td>
        <td class="main-table_td">{{ student.student.passport_id }}</td>
        <td class="main-table_td">{{ student.student.phone_number }}</td>
        <td class="main-table_td pen-box">
          <div class="pen-boxx">
            <a href="{% url 'del_s' student.id %}">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-trash"
                viewBox="0 0 16 16"
              >
                <path
                  d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"
                />
                <path
                  d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"
                />
              </svg>
            </a>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/staff/settings/groups.html
{% extends 'staff/base/base.html' %} {% load static %}
{% block title %} GURUHLAR
{% endblock title %} {% block style %}
<link rel="stylesheet" href="{% static 'staff/settings/groups_style.css' %}" />
{% endblock style %}
{% block content %}
<div class="boxes">
  <h3 class="give-book-title">Guruh qo'shish</h3>
  <div class="choose-input">
    <form method="post">
      {% csrf_token %}
      <input type="text" name="group" placeholder="Guruh raqami" required />
      <button type="submit">Qo'shish</button>
    </form>
  </div>
  <h3 class="existing-members">Mavjud guruhlar</h3>
  <div class="members-table">
    <table class="main-table">
      <thead>
        <tr class="main-table_tr">
          <th>T/R</th>
          <th>Guruh</th>
          <th>Talabalar soni</th>
          <th>O'chirish</th>
        </tr>
      </thead>
      <tbody>
        {% for group in groups %}
          <tr class="main-table_tr">
            <td class="main-table_td">{{ forloop.counter }}</td>
            <td class="main-table_td">{{ group.number }}</td>
            <td class="main-table_td">{{ group.students_set.all.count }}</td>
            <td class="main-table_td pen-box">
              <div class="pen-boxx">
                <a href="{% url 'del_g' group.id %}">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    fill="currentColor"
                    class="bi bi-trash"
                    viewBox="0 0 16 16"
                  >
                    <path
                      d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"
                    />
                    <path
                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"
                    />
                  </svg>
                </a>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/staff/settings/upload_book_data.html
{% extends 'staff/base/base.html' %} 
{% load static %} 
{% block title %} 
Kitob qo'shish 
{% endblock title %} 
{% block style %}
<link rel="stylesheet" href="{% static 'staff/settings/upload_book1.css' %}" />
{% endblock style %} 
{% block content %}

<div class="container">
  <div class="wrapper">
    <div class="upload-title">
      <p>Kitob ma'lumotlarini yuklash</p>
    </div>
    <div class="form-div">
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-div">
          <input type="file" name="file" id="upload-file" required hidden />
          <button id="upload-btn" type="button">Fayl tanlash</button>
          <span id="upload-text">Fayl tanlanmagan</span>
        </div>
        <div class="buttons-div">
          <div class="upload-btn-div">
            <button type="submit" class="submit-btn">Yuborish</button>
          </div>
          <div class="download-btn-div">
            <a href="{% static 'books.xlsx' %}" class="submit-btn-a" download>Namunani yuklash</a>
          </div>
          <div class="error-message-div">
            {% for messages in messages %} <p class="error-message-title">{{ messages }}</p> {% endfor %}
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script src="{% static 'staff/settings/upload_book1.js' %}"></script>

{% endblock content %}

templates/staff/settings/upload_student_data.html
{% extends 'staff/base/base.html' %}
{% load static %}
{% block title %}A'zo qo'shish{% endblock title %}
{% block style %}
  <link rel="stylesheet" href="{% static 'staff/settings/upload_book1.css' %}" />
{% endblock style %}
{% block content %}
<div class="container">
  <div class="wrapper">
    <div class="upload-title">
      <p>Talaba ma'lumotlarini yuklash</p>
    </div>
    <div class="form-div">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="select-div">
          <select
            name="group"
            class="form-control rounded"
            aria-label="Default select example"
          >
            <option>Guruh raqami</option>
            {% for group_id in group %}
            <option value="{{ group_id.id }}">{{ group_id.number }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="input-div">
          <input type="file" name="file" id="upload-file" required hidden />
          <button id="upload-btn" type="button">Fayl tanlash</button>
          <span id="upload-text">Fayl tanlanmagan</span>
        </div>
        <div class="buttons-div">
          <div class="upload-btn-div">
            <button type="submit" class="submit-btn">Yuborish</button>
          </div>
          <div class="download-btn-div">
            <a href="{% static 'student.xlsx' %}" class="submit-btn-a" download>Namunani yuklash</a>
          </div>
          <div class="error-message-div">
            {% for messages in messages %} <p class="error-message-title">{{ messages }}</p> {% endfor %}
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script src="{% static 'staff/settings/upload_book1.js' %}"></script>

{% endblock content %}